apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: pool-gatewayapi
spec:
  blocks:
    - start: 192.168.88.251
      stop: 192.168.88.251
  serviceSelector:
    matchLabels:
      io.cilium.gateway/owning-gateway: ciliumgw
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium
spec:
  controllerName: io.cilium/gateway-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ciliumgw
  labels:
    app: gateway
spec:
  gatewayClassName: cilium
  listeners:
  - name: https
    protocol: HTTPS
    port: 443
    tls:
      mode: Terminate
      certificateRefs:
      - name: nginx-tls