apiVersion: v1
kind: Namespace
metadata:
  name: codeserver
---
apiVersion: cilium.io/v2
kind: CiliumLoadBalancerIPPool
metadata:
  name: codeserver
spec:
  blocks:
    - start: 192.168.88.248
      stop: 192.168.88.248
  serviceSelector:
    matchLabels:
      app.kubernetes.io/instance: codeserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codeserver-pvc
  namespace: codeserver
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeserver
  namespace: codeserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeserver
  template:
    metadata:
      labels:
        app: codeserver
    spec:
      containers:
      - name: codeserver
        image: codercom/code-server:debian
        args:
        - /home/coder/project
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: datos
          mountPath: /home/coder/project
      volumes:
      - name: datos
        persistentVolumeClaim:
          claimName: codeserver-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: codeserver
  namespace: codeserver
  labels:
    app.kubernetes.io/instance: codeserver
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: codeserver
  type: LoadBalancer