apiVersion: v1
data:
  DB_POSTGRESDB_PASSWORD: Q29udHJhc2VueWEyMDI1Cg==
  POSTGRES_PASSWORD: Q29udHJhc2VueWEyMDI1Cg==
  WEBUI_SECRET_KEY: Q29udHJhc2VueWEyMDI1Cg==
kind: Secret
metadata:
  name: ia-pi-creds
  namespace: ia-pi
---
apiVersion: v1
data:
  tls.crt: CAMBIAME
  tls.key: CAMBIAME
  ca.crt: CAMBIAME
kind: Secret
metadata:
  name: n8n-tls-secret
  namespace: ia-pi
type: kubernetes.io/tls
---
apiVersion: v1
data:
  tls.crt: CAMBIAME
  tls.key: CAMBIAME
  ca.crt: CAMBIAME
kind: Secret
metadata:
  name: webui-tls-secret
  namespace: ia-pi
type: kubernetes.io/tls